import tkinter as Tk
import pygame 
pygame.init()
tkin = Tk.TK()
taille_ecran= (1355,695)
pygame.display.set_caption("ZCASINO")
fenetre = pygame.display.set_mode(taille_ecran)
color_fond = (255, 221, 51)
color_name = (93, 173, 226)
color_texte = (231, 76, 60)
p_name = pygame.font.SysFont("arial", 36)
p_texte = pygame.font.SysFont("arial",27 )
nom_IA1 = p_name.render("Bot 1", True, color_name)
image_IA1= pygame.image.load("electronics_new4.png")
nom_IA2 = p_name.render("Bot 2", True, color_name)
image_IA2= pygame.image.load("electronics_new4.png")
nom_IA3 = p_name.render("Bot 3", True, color_name)
image_IA3 = pygame.image.load("electronics_new4.png")
nom_player = p_name.render("Player", True, color_name)
image_player = pygame.image.load("user_new1.png")
mise_bot1 = p_texte.render("LA MISE", True, color_texte)
chiffre_bot1 = p_texte.render("SUR", True, color_texte)
mise_bot2 = p_texte.render("LA MISE", True, color_texte)
chiffre_bot2 = p_texte.render("SUR", True, color_texte)
mise_bot3 = p_texte.render("LA MISE", True, color_texte)
chiffre_bot3 = p_texte.render("SUR", True, color_texte)
mise_player = p_texte.render("LA MISE", True, color_texte)
chiffre_player = p_texte.render("SUR", True, color_texte)
label_bot1 = Tk.Label(tkin, text="_", font=("Tahoma", 16), bg='color_fond', fg='black')
label_bot1.pack()
quitter_jeu = True
while quitter_jeu :
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            quitter_jeu = False
        if event.type == pygame.MOUSEMOTION:
            print("{}".format(event.pos))
    fenetre.fill(color_fond) 
    fenetre.blit(nom_IA1, (480,6))
    fenetre.blit(image_IA1, (465,51))
    fenetre.blit(nom_IA2, (25,274))
    fenetre.blit(image_IA2, (14,321))
    fenetre.blit(nom_IA3, (1255,274))
    fenetre.blit(image_IA3, (1250,321))
    fenetre.blit(nom_player, (480, 548))
    fenetre.blit(image_player, (465, 594))
    fenetre.blit(mise_bot1, (580, 33))
    fenetre.blit(mise_bot2, (128, 295))
    fenetre.blit(mise_player, (580, 570))
    fenetre.blit(mise_bot3, (1145,290))
    pygame.display.flip()
tkin.mainloop()